### ISSUE TITLE
Enabling this plugin disrupts the spell checking

### ISSUE THREAD

**Issue by shuwens** [arzg/vim-rust-syntax-ext#2]
So this plugin actually disrupts the spell check in neovim, which by default only spell check comments. Is there a way to fix it?

<img width="891" alt="Screen Shot 2020-02-21 at 3 24 30 PM" src="https://user-images.githubusercontent.com/15823053/75069045-5f714680-54be-11ea-834b-086e2c23fb05.png">
<img width="894" alt="Screen Shot 2020-02-21 at 3 25 13 PM" src="https://user-images.githubusercontent.com/15823053/75069049-613b0a00-54be-11ea-8230-2afdaa1285e5.png">

**Comment by lunacookies** [comment]
Do you think it would be a good idea to enable spell check in doc comments, regular comments, as well as string literals?

**Comment by shuwens** [comment]
Yeah, I think that should be the case :)
