### ISSUE TITLE
/* */ comments are not highlighted

### ISSUE THREAD

**Issue by elomatreb** [arzg/vim-rust-syntax-ext#3]
Comments initiated with `/*` (are these block comments?) don't appear the same way "regular" comments do:
![5e522528abf3b2 07252529](https://user-images.githubusercontent.com/3387265/75105478-fb609680-5613-11ea-8ed2-2e6a1c567638.png)

**Comment by lunacookies** [comment]
Does something like this work?

```viml
" Append to after/syntax/rust.vim
syntax region rsBlockComment start='/\*' end='\*/'
highlight default link rsBlockComment rsComment
```

**Comment by elomatreb** [comment]
This does work for the reasonable simple case, thanks! Block comments can be nested (https://doc.rust-lang.org/reference/comments.html), and it doesn't work for those, but I'm not sure if that's actually common.

**Comment by Dowwie** [comment]
I second this request for improved support of comment blocks
